#!/bin/bash
# written by Philipp Resl

if [[ "$OSTYPE" == "darwin"* ]]; then
 HT="darwin"
 US="root"
else
 HT="linux"
 US=$USER
fi

# this needs to be set because on Linux docker created files will be owned by root by default.
unset DOCKER_USER
if [[ "$OSTYPE" == "linux-gnu" ]]; then
 DOCKER_USER="--user $(id -u):$(id -g)"
elif [[ "$OSTYPE" == "darwin"* ]]; then #nothing to be done on MacOS
 DOCKER_USER=""
fi
BINDPOINTS="-v $(pwd):/data"

docker run --rm -it $DOCKER_USER $BINDPOINTS -w /data reslp/amplipiper:3d41924 AmpliPiper.sh $@	
#Command will look something like this:
#docker run --rm -it --user $(id -u):$(id -g) -v $(pwd):/home/$USER/phylociraptor --privileged reslp/phylociraptor:0.9.1
